= oci-gradle-build-cache-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    oci-gradle-build-cache-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.3.0

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]

---

This is a custom Gradle link:https://docs.gradle.org/current/userguide/build_cache.html[build cache] implementation which uses the link:https://www.oracle.com/cloud/[Oracle Cloud] to store the cache objects.

WARNING:  This plugin is not endorsed by Oracle nor does the company provide any support for it.

== Prerequisites

1. An Oracle Cloud account. Sign up for an Always Free tier account at at link:http://oracle.com/cloud/free[].
2. A resource compartment. It's recommended to use a compartment different than the default `root`.
3. Setup an Object Lifecycle Policy on the compartment. Refer to link:https://docs.cloud.oracle.com/iaas/Content/Object/Tasks/usinglifecyclepolicies.htm[]

Gradle 5.x and Java 8 are the minimum requirements to run this plugin.

== Usage

Add the following to your `settings.gradle` file

[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}

apply plugin: '{project-group}.oci-build-cache'
----

== Configuration

Add the following to your `settings.gradle` file

[source,groovy]
[subs="attributes,verbatim"]
----
ext.isCiServer = System.getenv().containsKey('CI')

buildCache {
    local {
        enabled = !isCiServer
    }
    remote(org.kordamp.gradle.plugin.buildcache.OCIBuildCache) {
        compartmentId = <compartment-id>
        push = isCiServer
    }
}
----

The plugin offers the following configuration properties

[options="header"]
|===
| Configuration Key | Description                      | Mandatory | Default Value
| configFile        | Location of the config file      | no        | ~/.oci/config
| profile           | Name of the OCI profile to use   | no        | DEFAULT
| compartmentId     | Compartment that owns the bucket | yes       |
| bucket            | Bucket name                      | no        | build-cache
| policy            | Object lifecycle policy (DELETE) | no        | amount: 30L, unit: days
|===

The default object lifecycle policy is to delete cached items after 30 days. You can change these defaults with the following snippet

[source,groovy]
[subs="attributes,verbatim"]
.settings.gradle
----
buildCache {
    local {
        enabled = !isCiServer
    }
    remote(org.kordamp.gradle.plugin.buildcache.OCIBuildCache) {
        compartmentId = <compartment-id>
        push = isCiServer
        policy {
            amount = 90L // 3 months
        }
    }
}
----

You can configure authentication in two ways:

 1. Using the standard configuration file, typically located at `~/.oci/config`.
 2. Defining a `config` block on the `remote` block.

=== Standard Config File

The format of the configuration file is specified at link:https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdkgettingstarted.htm[this page],
it looks something similar to

[source,groovy]
[subs="attributes,verbatim"]
.~/.oci/config
----
[DEFAULT]
user=ocid1.user.oc1...
tenancy=ocid1.tenancy.oc1...
region=eu-frankfurt-1
key_file=~/.oci/oci_api_key.pem
pass_phrase=<secret>
fingerprint=f9:14:d0:...
----

=== Config Block

Alternatively you may define a `config` block. This block defines properties that match settings found on the config file

[source,groovy]
[subs="attributes,verbatim"]
.settings.gradle
----
buildCache {
    local {
        enabled = !isCiServer
    }
    remote(org.kordamp.gradle.plugin.buildcache.OCIBuildCache) {
        compartmentId = <compartment-id>
        bucket = <bucket-name>
        push = isCiServer
        config {
            userId      = 'ocid1.user.oc1...'
            tenantId    = 'ocid1.tenancy.oc1...'
            region      = 'eu-frankfurt-1'
            keyfile     = '~/.oci/oci_api_key.pem'
            passphrase  = '<secret>'
            fingerprint = 'f9:14:d0:...'
        }
    }
}
----

More details about configuring the Gradle build cache can be found in the
link:https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_configure[official Gradle documentation].

